# Default values for max-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: max-gitops-exercise-helm
configMapData: max-nginx-helm-cm-data
hostPrefix: hello-exercise
hostSuffix: .platform.ele.dev
items:
  - 1
  - 2
  - 3
  - 4
  - 5
port: 80

image: nginx:1.23-alpine

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
