---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    name: max-gitops-exercise
  name: max-gitops-exercise
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: max-nginx-configmap
  namespace: max-gitops-exercise
data:
  hello_1: |
    Hello from pod number 1
  hello_2: |
    Hello from pod number 2
---
apiVersion: v1
kind: Pod
metadata:
  name: max-nginx-1
  namespace: max-gitops-exercise
  labels:
    name: max-nginx-1
    app: max-nginx
spec:
  volumes:
    - name: html-volume
      configMap:
        name: max-nginx-configmap
  containers:
    - name: max-nginx-1
      image: nginx:stable
      ports:
        - containerPort: 80
          name: http-web-svc
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: hello_1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: max-nginx-2
  namespace: max-gitops-exercise
  labels:
    name: max-nginx-2
    app: max-nginx
spec:
  volumes:
    - name: html-volume
      configMap:
        name: max-nginx-configmap
  containers:
    - name: max-nginx-2
      image: nginx:stable
      ports:
        - containerPort: 80
          name: http-web-svc
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: hello_2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service
  namespace: max-gitops-exercise
spec:
  selector:
    app: max-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service-1
  namespace: max-gitops-exercise
spec:
  selector:
    name: max-nginx-1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service-2
  namespace: max-gitops-exercise
spec:
  selector:
    name: max-nginx-2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingress-max-gitops-vs
  namespace: max-gitops-exercise
spec:
  gateways:
  - istio-ingress/platform-ingress-gateway
  hosts:
  - hello-exercise.platform.ele.dev
  http:
  - route:
    - destination:
        host: max-nginx-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingress-max-gitops-vs-1
  namespace: max-gitops-exercise
spec:
  gateways:
  - istio-ingress/platform-ingress-gateway
  hosts:
  - hello-exercise-1.platform.ele.dev
  http:
  - route:
    - destination:
        host: max-nginx-service-1
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingress-max-gitops-vs-2
  namespace: max-gitops-exercise
spec:
  gateways:
  - istio-ingress/platform-ingress-gateway
  hosts:
  - hello-exercise-2.platform.ele.dev
  http:
  - route:
    - destination:
        host: max-nginx-service-2
        port:
          number: 80
