---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
    name: max-gitops-exercise
  name: max-gitops-exercise
---
apiVersion: v1
kind: Pod
metadata:
  name: max-nginx
  labels:
    name: max-nginx
  namespace: max-gitops-exercise
spec:
  containers:
  - name: max-nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service
  namespace: max-gitops-exercise
spec:
  selector:
    name: max-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ingress-max-gitops-vs
  namespace: max-gitops-exercise
spec:
  gateways:
  - istio-ingress/platform-ingress-gateway
  hosts:
  - hello-exercise-1.platform.ele.dev
  http:
  - route:
    - destination:
        host: max-nginx-service
        port:
          number: 80
