---
apiVersion: v1
kind: ConfigMap
metadata:
  name: max-nginx-configmap
  namespace: max-gitops-exercise
data:
  hello-1: |
    Hello from pod number 1
  hello-2: |
    Hello from pod number 2
  hello-3: |
    Hello from pod number 3
  hello-4: |
    Hello from pod number 4
  hello-5: |
    Hello from pod number 5
