---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service
  namespace: max-gitops-exercise
spec:
  selector:
    app: max-nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
