---
apiVersion: v1
kind: Service
metadata:
  name: max-nginx-service-5
  namespace: max-gitops-exercise
spec:
  selector:
    name: max-nginx-5
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  type: ClusterIP
