apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- range $.Values.items }}
  {{ $.Values.configMapData }}-{{ . }}: |
    Hello from pod number {{ . }}
  {{- end }}
