---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-service
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $.Chart.Name }}-app
  ports:
  - name: http
    protocol: TCP
    port: {{ $.Values.port }}
    targetPort: {{ $.Chart.Name }}-port
  type: ClusterIP
