apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{ $.Values.configMapData }}: |
    <?php echo "Hello from pod " . $_ENV["MY_POD_NAME"]; ?>
