apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{ $.Values.configMapData }}: |
    <?php echo "Hello from pod " . $_ENV["POD_NAME"] . " in environment " . "{{ .Values.environment }}"; ?>
