---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-service
spec:
  selector:
    name: {{ $.Chart.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ $.Values.port }}
    targetPort: {{ $.Chart.Name }}-port
  type: ClusterIP
