---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Chart.Name }}-vs
spec:
  gateways:
  - istio-ingress/platform-ingress-gateway
  hosts:
  - {{ $.Values.host }}
  http:
  - route:
    - destination:
        host: {{ $.Chart.Name }}-service
        port:
          number: 80
